stages:
  - check-release
  - get-dependencies
  - build
  - upload
  - release

.on-merge-request:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.not-merge-request:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

.on-master:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.golang-job:
  image: golang:1.24
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

check-release:
  extends:
  - .on-merge-request
  - .on-master
  stage: check-release
  script:
    - ./releasetools gitlab checkReleaseBranch
    - export VERSION=$(./releasetools getLatestVersion)
    - echo "VERSION=$VERSION" >> .env
  artifacts:
    reports:
      dotenv:
        - .env

get-dependencies:
  extends:
    - .golang-job
    - .not-merge-request
  stage: get-dependencies
  script:
    - go get

build-windows:
  extends:
    - .on-master
    - .golang-job
  stage: build
  script:
    - mkdir -p output
    - export GOOS=windows
    - export GOARCH=amd64
    - go build -o output/streamres.exe
  artifacts:
    paths:
      - output/streamres.exe

upload-windows:
  extends:
    - .on-master
  stage: upload
  script: |
    curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
       --upload-file output/streamres.exe \
       ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/streamres/${VERSION}/streamres.exe

create-release:
  extends:
    - .on-master
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - export CHANGES=$(./releasetools extractChanges $VERSION)
  release:
    name: "Streamres Release $VERSION"
    tag_name: $VERSION
    description: "${CHANGES}"
    assets:
      links:
        - name: "Streamres Windows $VERSION"
          link_type: package
          url: https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/generic/streamres/${VERSION}/streamres.exe